apiVersion: v1
kind: Service
metadata:
  name: cancer-ui
  namespace: rclone
  labels:
    app: cancer-ui
spec:
  selector:
    app: cancer-ui
  type: NodePort
  ports:
  - name: app-port
    port: 8080
    targetPort: 8080